-- ============================================================
-- AI Daily Terms — Migration 003
-- Enrich terms table + upsert 32 terms from v1 Seed Pack
-- Run this in Supabase SQL Editor (or via CLI)
-- ============================================================

-- ── 1. Schema: add enrichment + quiz columns ────────────────

ALTER TABLE public.terms
  ADD COLUMN IF NOT EXISTS short_definition  text,
  ADD COLUMN IF NOT EXISTS plain_explanation  text,
  ADD COLUMN IF NOT EXISTS use_case          text,
  ADD COLUMN IF NOT EXISTS why_it_matters    text,
  ADD COLUMN IF NOT EXISTS common_mistake    text,
  ADD COLUMN IF NOT EXISTS related_terms     text[],
  ADD COLUMN IF NOT EXISTS quiz_question     text,
  ADD COLUMN IF NOT EXISTS quiz_type         text,
  ADD COLUMN IF NOT EXISTS option_a          text,
  ADD COLUMN IF NOT EXISTS option_b          text,
  ADD COLUMN IF NOT EXISTS option_c          text,
  ADD COLUMN IF NOT EXISTS option_d          text,
  ADD COLUMN IF NOT EXISTS correct_answer    text,
  ADD COLUMN IF NOT EXISTS quiz_explanation  text;

-- ── 2. Upsert 32 terms ──────────────────────────────────────
-- On conflict (slug, vertical_id):
--   • NEW columns are populated for all terms
--   • definition / category / difficulty preserved for existing rows
-- ─────────────────────────────────────────────────────────────

INSERT INTO public.terms (
  vertical_id, slug, term, definition,
  category, difficulty, published,
  short_definition, plain_explanation, use_case, why_it_matters,
  common_mistake, related_terms,
  quiz_question, quiz_type,
  option_a, option_b, option_c, option_d,
  correct_answer, quiz_explanation
) VALUES

-- 1 ──────────────────────────────────────────────────────────
('general', 'artificial-intelligence', 'Artificial Intelligence',
 'Artificial intelligence is the ability of computer systems to perform tasks that usually require human thinking.',
 'AI Basics', 'beginner', true,
 'Artificial intelligence is the ability of computer systems to perform tasks that usually require human thinking.',
 'Basically, what this means is a machine can analyze information, recognize patterns, make suggestions, or create content in ways that feel intelligent.',
 'A customer service chatbot answers common questions without a human agent handling every request.',
 'People hear the term AI everywhere. Understanding the umbrella term helps beginners make sense of all the other related concepts.',
 'Thinking AI always means human-like robots. In reality, most AI today works quietly inside software systems.',
 ARRAY['Machine Learning','Model','Automation'],
 'Which statement best describes artificial intelligence?', 'multiple_choice',
 'A machine that only stores files',
 'A computer system performing tasks that usually require human thinking',
 'A type of internet connection',
 'A spreadsheet formula',
 'B',
 'AI refers broadly to systems that can perform tasks such as prediction, language generation, classification, or decision support.'),

-- 2 ──────────────────────────────────────────────────────────
('general', 'machine-learning', 'Machine Learning',
 'Machine learning is a type of AI where systems learn patterns from data instead of being programmed step by step.',
 'AI Basics', 'beginner', true,
 'Machine learning is a type of AI where systems learn patterns from data instead of being programmed step by step.',
 'We give the system examples, and it learns from those examples to make future predictions or decisions.',
 'An email system learns to spot spam by analyzing large numbers of past messages.',
 'Many AI tools people use every day are powered by machine learning, so this is one of the most important foundation terms.',
 'Assuming the system understands information the way a person does. It is really identifying patterns in data.',
 ARRAY['Artificial Intelligence','Training Data','Model'],
 'What makes machine learning different from traditional programming?', 'multiple_choice',
 'It uses data to learn patterns',
 'It only works offline',
 'It cannot make predictions',
 'It does not use computers',
 'A',
 'Machine learning learns from data patterns rather than relying only on fixed step-by-step instructions.'),

-- 3 ── NEW ────────────────────────────────────────────────────
('general', 'model', 'Model',
 'A model is the trained AI system that uses learned patterns to produce outputs.',
 'AI Basics', 'beginner', true,
 'A model is the trained AI system that uses learned patterns to produce outputs.',
 'You can think of a model as the working brain of the AI tool after training has been completed.',
 'A fraud detection model reviews transactions and flags ones that look unusual.',
 'When people say they are using an AI model, they mean the actual system doing the prediction or generation.',
 'Confusing the model with the app interface. The app is what users see; the model is the engine underneath.',
 ARRAY['Machine Learning','Training Data','Inference'],
 'In AI, what is a model?', 'multiple_choice',
 'A design mockup only',
 'The trained system that produces outputs',
 'A type of keyboard',
 'A storage device',
 'B',
 'The model is the trained system that performs the AI task.'),

-- 4 ──────────────────────────────────────────────────────────
('general', 'training-data', 'Training Data',
 'Training data is the information used to teach an AI model.',
 'Data and Training', 'beginner', true,
 'Training data is the information used to teach an AI model.',
 'If the model is the worker, training data is the instruction and examples used during training.',
 'A speech recognition system is trained on many hours of spoken audio and text transcripts.',
 'Good data supports good results. Poor or biased data can lead to weak or unfair outputs.',
 'Believing more data always means better outcomes. Quality and relevance matter just as much as quantity.',
 ARRAY['Dataset','Bias','Fine-Tuning'],
 'Why is training data important?', 'multiple_choice',
 'It powers the computer screen',
 'It teaches the AI model patterns',
 'It only stores passwords',
 'It replaces the model',
 'B',
 'Training data is what the model learns from.'),

-- 5 ── NEW ────────────────────────────────────────────────────
('general', 'dataset', 'Dataset',
 'A dataset is a collection of data used for analysis, training, testing, or evaluation.',
 'Data and Training', 'beginner', true,
 'A dataset is a collection of data used for analysis, training, testing, or evaluation.',
 'A dataset may include text, images, audio, numbers, or labels grouped together for a specific purpose.',
 'A company creates a dataset of customer reviews to train a sentiment analysis system.',
 'Beginners will hear this term often because data is at the heart of AI systems.',
 'Thinking every dataset is ready to use. Many need cleaning, labeling, or organizing first.',
 ARRAY['Training Data','Labelled Data','Evaluation'],
 'What is a dataset?', 'multiple_choice',
 'A group of organized data',
 'A payment processor',
 'A type of screen resolution',
 'A website theme',
 'A',
 'A dataset is simply a structured collection of data.'),

-- 6 ──────────────────────────────────────────────────────────
('general', 'large-language-model', 'Large Language Model',
 'A large language model is an AI system trained on massive amounts of text to understand and generate language.',
 'Language AI', 'beginner', true,
 'A large language model is an AI system trained on massive amounts of text to understand and generate language.',
 'This is the technology behind many chat-based AI tools. It predicts useful text based on your input.',
 'A user asks an AI assistant to summarize a report or draft an email.',
 'LLMs are central to today''s AI tools, so beginners need to know what powers the experience.',
 'Assuming an LLM always knows facts. It generates likely language and still needs verification.',
 ARRAY['Prompt','Token','Context Window'],
 'What does an LLM mainly work with?', 'multiple_choice',
 'Concrete and steel',
 'Human language',
 'Only spreadsheets',
 'Video cables',
 'B',
 'LLMs are built to process and generate language.'),

-- 7 ── NEW ────────────────────────────────────────────────────
('general', 'prompt', 'Prompt',
 'A prompt is the instruction or question you give an AI system.',
 'Prompting', 'beginner', true,
 'A prompt is the instruction or question you give an AI system.',
 'The prompt tells the AI what you want. Better prompts usually lead to better answers.',
 'A user types: Write a beginner-friendly explanation of machine learning with one real-world example.',
 'Prompt quality directly affects output quality, especially in language-based AI tools.',
 'Using vague prompts and expecting precise results.',
 ARRAY['Prompt Engineering','Output','System Prompt'],
 'Which of these is a prompt?', 'multiple_choice',
 'Write a 5-point summary of this article',
 'A hidden software bug',
 'A browser tab',
 'A hard drive type',
 'A',
 'A prompt is the instruction you give the AI.'),

-- 8 ──────────────────────────────────────────────────────────
('general', 'prompt-engineering', 'Prompt Engineering',
 'Prompt engineering is the practice of designing prompts to get better results from AI.',
 'Prompting', 'beginner', true,
 'Prompt engineering is the practice of designing prompts to get better results from AI.',
 'It is about being intentional with wording, structure, examples, and constraints so the AI gives you more useful output.',
 'A trainer creates a prompt that asks AI to write a safety talk in plain language with a real workplace example and supervisor action steps.',
 'A small improvement in prompting can lead to a major improvement in the usefulness of the answer.',
 'Thinking prompt engineering is only for programmers. In reality, any user can benefit from it.',
 ARRAY['Prompt','Few-Shot Prompting','Constraint'],
 'What is the goal of prompt engineering?', 'multiple_choice',
 'To make prompts more effective',
 'To replace databases',
 'To build computers',
 'To remove all human review',
 'A',
 'Prompt engineering is about improving AI instructions so results are more useful and reliable.'),

-- 9 ── NEW ────────────────────────────────────────────────────
('general', 'token', 'Token',
 'A token is a small unit of text that an AI model processes.',
 'Language AI', 'beginner', true,
 'A token is a small unit of text that an AI model processes.',
 'A token may be a word, part of a word, punctuation, or a short text fragment depending on the model.',
 'A long document uses more tokens than a short question, which affects processing limits and sometimes cost.',
 'Understanding tokens helps users make sense of context limits, pricing, and long prompts.',
 'Assuming one token always equals one word. That is not always true.',
 ARRAY['Context Window','Large Language Model','Inference'],
 'Why do tokens matter in AI tools?', 'multiple_choice',
 'They affect how text is processed',
 'They replace internet access',
 'They are only used in photos',
 'They are computer fans',
 'A',
 'Tokens are the text units an AI processes, so they affect limits and performance.'),

-- 10 ─────────────────────────────────────────────────────────
('general', 'context-window', 'Context Window',
 'The context window is the amount of text an AI model can consider at one time.',
 'Language AI', 'beginner', true,
 'The context window is the amount of text an AI model can consider at one time.',
 'Think of it as the model''s working memory during a conversation or task.',
 'If a user uploads a long report, the model may only be able to consider part of it depending on its context window.',
 'It explains why AI sometimes forgets earlier details or struggles with very long inputs.',
 'Believing the model remembers everything forever. It only processes what fits in context.',
 ARRAY['Token','Large Language Model','Prompt'],
 'What does the context window describe?', 'multiple_choice',
 'A laptop screen size',
 'The amount of text the model can consider at once',
 'A printer setting',
 'A cloud storage limit',
 'B',
 'The context window is the model''s working range for text input and output.'),

-- 11 ── NEW ───────────────────────────────────────────────────
('general', 'output', 'Output',
 'Output is the result produced by the AI after it processes your prompt or input.',
 'Language AI', 'beginner', true,
 'Output is the result produced by the AI after it processes your prompt or input.',
 'The output can be text, an image, a recommendation, a classification, or another generated result.',
 'An AI system produces a draft email after receiving your instructions.',
 'Beginners need to understand that the AI''s answer is an output, not automatically a verified truth.',
 'Treating every AI output as final and correct without review.',
 ARRAY['Prompt','Inference','Hallucination'],
 'What is an AI output?', 'multiple_choice',
 'The instruction you type',
 'The result the AI produces',
 'The training data only',
 'The login page',
 'B',
 'The output is the result returned by the AI.'),

-- 12 ─────────────────────────────────────────────────────────
('general', 'inference', 'Inference',
 'Inference is the process of using a trained AI model to generate a prediction or response.',
 'Language AI', 'intermediate', true,
 'Inference is the process of using a trained AI model to generate a prediction or response.',
 'Training is when the model learns. Inference is when the trained model is actually used.',
 'When you ask an AI chatbot a question and it replies, that response is produced during inference.',
 'This term helps users understand the difference between building a model and using one.',
 'Confusing inference with training.',
 ARRAY['Model','Output','Large Language Model'],
 'When does inference happen?', 'multiple_choice',
 'When the AI is being used to produce an answer',
 'Only when a website is designed',
 'Only during payment processing',
 'Only before data exists',
 'A',
 'Inference is the live use of the trained model.'),

-- 13 ─────────────────────────────────────────────────────────
('general', 'fine-tuning', 'Fine-Tuning',
 'Fine-tuning is the process of adjusting a trained model with additional specialized data.',
 'Data and Training', 'beginner', true,
 'Fine-tuning is the process of adjusting a trained model with additional specialized data.',
 'We start with a general model, then refine it using more focused examples so it performs better in a specific area.',
 'A company fine-tunes a model on its customer support conversations to improve responses in that domain.',
 'This helps beginners understand how general AI tools can become more specialized.',
 'Thinking fine-tuning is the same as simply adding documents for search. It is a different process.',
 ARRAY['Training Data','RAG','Model'],
 'What is the purpose of fine-tuning?', 'multiple_choice',
 'To specialize a trained model further',
 'To unplug a server',
 'To create a password',
 'To reduce screen brightness',
 'A',
 'Fine-tuning customizes a model with additional focused training data.'),

-- 14 ─────────────────────────────────────────────────────────
('general', 'supervised-learning', 'Supervised Learning',
 'Supervised learning is a type of machine learning where the model learns from labeled examples.',
 'Data and Training', 'beginner', true,
 'Supervised learning is a type of machine learning where the model learns from labeled examples.',
 'The system is shown inputs and the correct answers so it can learn the relationship between them.',
 'A model learns to classify emails as spam or not spam using examples already labeled by people.',
 'This is one of the most common learning methods in AI.',
 'Thinking all AI learns without guidance. Many models rely on labeled examples.',
 ARRAY['Machine Learning','Labelled Data','Classification'],
 'What makes supervised learning supervised?', 'multiple_choice',
 'It uses labeled examples',
 'It needs no data',
 'It only works on weekends',
 'It removes all human input',
 'A',
 'Supervised learning uses examples with known correct answers.'),

-- 15 ─────────────────────────────────────────────────────────
('general', 'unsupervised-learning', 'Unsupervised Learning',
 'Unsupervised learning is a type of machine learning that finds patterns in data without labeled answers.',
 'Data and Training', 'intermediate', true,
 'Unsupervised learning is a type of machine learning that finds patterns in data without labeled answers.',
 'The model explores the data to discover structure, groups, or relationships on its own.',
 'A retailer groups customers into segments based on behavior patterns without predefined labels.',
 'It helps beginners understand that not all AI requires pre-labeled data.',
 'Assuming unsupervised learning means random guessing. It still looks for meaningful patterns.',
 ARRAY['Machine Learning','Clustering','Dataset'],
 'What is true about unsupervised learning?', 'multiple_choice',
 'It uses no labels for the target answers',
 'It only works with robots',
 'It cannot find patterns',
 'It is the same as typing a prompt',
 'A',
 'Unsupervised learning looks for structure in unlabeled data.'),

-- 16 ─────────────────────────────────────────────────────────
('general', 'reinforcement-learning', 'Reinforcement Learning',
 'Reinforcement learning is a method where an AI learns by receiving rewards or penalties based on its actions.',
 'Data and Training', 'intermediate', true,
 'Reinforcement learning is a method where an AI learns by receiving rewards or penalties based on its actions.',
 'The system tries actions, gets feedback, and improves over time by aiming for better results.',
 'A game-playing AI learns strategies by getting rewarded for successful moves and penalized for poor ones.',
 'This explains another major way AI systems can improve, especially in decision-making tasks.',
 'Assuming reinforcement learning is the same as simple rule-based programming.',
 ARRAY['Machine Learning','Reward','Policy'],
 'How does reinforcement learning improve?', 'multiple_choice',
 'By trial, feedback, rewards, and penalties',
 'By deleting all data',
 'By changing monitor settings',
 'By ignoring outcomes',
 'A',
 'Reinforcement learning improves through feedback from actions.'),

-- 17 ─────────────────────────────────────────────────────────
('general', 'generative-ai', 'Generative AI',
 'Generative AI is AI that creates new content such as text, images, audio, or video.',
 'Content and Media AI', 'beginner', true,
 'Generative AI is AI that creates new content such as text, images, audio, or video.',
 'Instead of only analyzing data, it produces something new based on patterns it learned during training.',
 'A user asks AI to create a course outline or generate a promotional image.',
 'This is the kind of AI most beginners are interacting with today.',
 'Thinking generated content is always original, accurate, or free from error.',
 ARRAY['Large Language Model','Image Generation','Hallucination'],
 'What is a common use of generative AI?', 'multiple_choice',
 'Creating new content',
 'Replacing all electricity',
 'Repairing hardware only',
 'Storing paper files',
 'A',
 'Generative AI is used to create content such as text, images, or audio.'),

-- 18 ─────────────────────────────────────────────────────────
('general', 'hallucination', 'Hallucination',
 'A hallucination is when AI produces false or made-up information as if it were true.',
 'Risk and Ethics', 'beginner', true,
 'A hallucination is when AI produces false or made-up information as if it were true.',
 'The answer may sound polished and confident, but it can still be wrong.',
 'An AI assistant invents a regulation number that does not actually exist.',
 'This is one of the most important risks users need to understand before relying on AI outputs.',
 'Believing that fluent language means factual accuracy.',
 ARRAY['Output','Accuracy','Human Oversight'],
 'What is the main risk of an AI hallucination?', 'multiple_choice',
 'False information presented as fact',
 'Slow internet speed',
 'A broken keyboard',
 'Extra screen brightness',
 'A',
 'A hallucination is a false answer that sounds convincing.'),

-- 19 ── NEW ───────────────────────────────────────────────────
('general', 'bias', 'Bias',
 'Bias in AI refers to unfair or distorted patterns in data or model outputs.',
 'Risk and Ethics', 'beginner', true,
 'Bias in AI refers to unfair or distorted patterns in data or model outputs.',
 'If the training data has imbalances or unfair patterns, the AI can reflect or amplify them.',
 'A hiring tool ranks some applicants unfairly because of biased historical data.',
 'Bias can create legal, ethical, and trust problems in real-world systems.',
 'Thinking bias only comes from the model itself. Data and human choices also play a major role.',
 ARRAY['Training Data','Fairness','Governance'],
 'Where can AI bias come from?', 'multiple_choice',
 'Only from the user''s screen',
 'From data, design choices, and model behavior',
 'Only from printers',
 'Only from internet speed',
 'B',
 'Bias can come from many sources, especially data and design decisions.'),

-- 20 ── NEW ───────────────────────────────────────────────────
('general', 'explainability', 'Explainability',
 'Explainability is the ability to understand how or why an AI system reached a result.',
 'Risk and Ethics', 'beginner', true,
 'Explainability is the ability to understand how or why an AI system reached a result.',
 'It means we can make sense of the AI''s reasoning or the factors behind a decision.',
 'A bank wants to explain why an AI system denied a loan application.',
 'Explainability is important when decisions affect people, compliance, or trust.',
 'Assuming all advanced AI systems are easy to explain. Some are much harder to interpret than others.',
 ARRAY['Transparency','Governance','Human Oversight'],
 'Why is explainability important?', 'multiple_choice',
 'It helps people understand AI decisions',
 'It makes batteries larger',
 'It removes all errors automatically',
 'It only matters for gaming',
 'A',
 'Explainability helps users and organizations understand AI decisions.'),

-- 21 ── NEW ───────────────────────────────────────────────────
('general', 'ai-governance', 'AI Governance',
 'AI governance is the system of rules, responsibilities, and oversight used to manage AI safely and responsibly.',
 'Risk and Ethics', 'beginner', true,
 'AI governance is the system of rules, responsibilities, and oversight used to manage AI safely and responsibly.',
 'It defines who is accountable, what standards apply, and how AI use is monitored.',
 'A company creates approval and review procedures before staff can deploy AI tools in customer-facing work.',
 'Good governance helps reduce risk, protect users, and support due diligence.',
 'Thinking governance only matters in large corporations. Even small teams need basic controls.',
 ARRAY['Bias','Explainability','Data Privacy'],
 'What is the purpose of AI governance?', 'multiple_choice',
 'To manage AI use responsibly',
 'To design office furniture',
 'To increase file sizes',
 'To replace all managers',
 'A',
 'Governance provides structure, accountability, and oversight for AI use.'),

-- 22 ── NEW ───────────────────────────────────────────────────
('general', 'data-privacy', 'Data Privacy',
 'Data privacy means protecting personal or sensitive information from improper use, access, or disclosure.',
 'Risk and Ethics', 'beginner', true,
 'Data privacy means protecting personal or sensitive information from improper use, access, or disclosure.',
 'When AI tools process data, we need to be careful about what information is shared and how it is handled.',
 'A company avoids pasting confidential employee information into a public AI tool.',
 'Privacy mistakes can create legal, ethical, and reputational problems.',
 'Assuming every AI tool handles confidential information the same way.',
 ARRAY['Governance','Security','Human Oversight'],
 'What is a good data privacy practice?', 'multiple_choice',
 'Sharing confidential data freely',
 'Being careful about what sensitive data is entered into AI tools',
 'Ignoring company rules',
 'Posting passwords publicly',
 'B',
 'Good privacy practice includes limiting exposure of sensitive information.'),

-- 23 ─────────────────────────────────────────────────────────
('general', 'api', 'API',
 'An API is a method that allows different software systems to communicate with each other.',
 'Automation and Tools', 'beginner', true,
 'An API is a method that allows different software systems to communicate with each other.',
 'It acts like a bridge so one app can send a request to another app and receive data back.',
 'A website sends a prompt to an AI service through an API and displays the returned answer to the user.',
 'APIs are what make modern software integrations and AI-powered workflows possible.',
 'Thinking an API is only for developers. Users benefit from APIs every time connected tools work together.',
 ARRAY['Integration','Webhook','Automation'],
 'What does an API mainly do?', 'multiple_choice',
 'Helps software systems communicate',
 'Cleans computer screens',
 'Prints labels only',
 'Charges batteries',
 'A',
 'An API enables communication and data exchange between systems.'),

-- 24 ── NEW ───────────────────────────────────────────────────
('general', 'automation', 'Automation',
 'Automation is the use of technology to carry out tasks with reduced manual effort.',
 'Automation and Tools', 'beginner', true,
 'Automation is the use of technology to carry out tasks with reduced manual effort.',
 'Instead of repeating the same steps by hand, we set up a system to perform them consistently.',
 'A workflow automatically sends a summary email after an AI tool processes a report.',
 'Automation is one of the biggest practical benefits people get from AI and connected systems.',
 'Thinking automation removes all human responsibility. People still need oversight and quality control.',
 ARRAY['Workflow','API','AI Agent'],
 'What is a major benefit of automation?', 'multiple_choice',
 'Reducing manual repetitive work',
 'Making tasks harder to complete',
 'Removing all review forever',
 'Disconnecting systems',
 'A',
 'Automation helps reduce repetitive manual work.'),

-- 25 ── NEW ───────────────────────────────────────────────────
('general', 'workflow', 'Workflow',
 'A workflow is a sequence of steps used to complete a task or process.',
 'Automation and Tools', 'beginner', true,
 'A workflow is a sequence of steps used to complete a task or process.',
 'In AI and software, workflows connect actions so that information moves from one step to the next.',
 'A workflow takes a form submission, sends it to AI for summarization, then stores the result in a database.',
 'Beginners often hear about AI workflows because real value usually comes from connecting AI to business processes.',
 'Thinking AI alone solves a problem. Often the workflow around the AI matters just as much.',
 ARRAY['Automation','API','Integration'],
 'What is a workflow?', 'multiple_choice',
 'A sequence of connected task steps',
 'A type of chair',
 'A password manager only',
 'A video file',
 'A',
 'A workflow is the structured sequence of steps used to get work done.'),

-- 26 ── NEW ───────────────────────────────────────────────────
('general', 'ai-agent', 'AI Agent',
 'An AI agent is a system that can make decisions or take actions to help complete tasks.',
 'Automation and Tools', 'beginner', true,
 'An AI agent is a system that can make decisions or take actions to help complete tasks.',
 'Instead of only replying to a question, an agent may plan steps, use tools, and carry out actions.',
 'An AI agent reads an incoming request, drafts a response, and creates a follow-up task automatically.',
 'Agents are becoming a major topic in AI because they move beyond simple chat responses.',
 'Assuming agents can be left unsupervised for everything. They still need boundaries and review.',
 ARRAY['Automation','Tool Calling','Workflow'],
 'How is an AI agent different from a basic chatbot?', 'multiple_choice',
 'It can take actions or coordinate steps',
 'It has no software behind it',
 'It only works on paper',
 'It cannot use tools',
 'A',
 'An AI agent is designed to do more than answer; it can act or orchestrate tasks.'),

-- 27 ── NEW ───────────────────────────────────────────────────
('general', 'rag', 'RAG',
 'RAG stands for Retrieval-Augmented Generation, a method where AI retrieves relevant information before generating an answer.',
 'Search and Knowledge', 'beginner', true,
 'RAG stands for Retrieval-Augmented Generation, a method where AI retrieves relevant information before generating an answer.',
 'Instead of guessing from memory alone, the AI first looks up trusted source material, then uses it to respond.',
 'A company chatbot searches internal policy documents before answering a staff question.',
 'RAG can improve accuracy and help reduce hallucinations in practical business use.',
 'Confusing RAG with fine-tuning. RAG retrieves information at response time; fine-tuning changes the model.',
 ARRAY['Knowledge Base','Embedding','Vector Database'],
 'What is the main benefit of RAG?', 'multiple_choice',
 'Using retrieved source information to improve answers',
 'Making keyboards silent',
 'Replacing all databases forever',
 'Reducing internet speed',
 'A',
 'RAG improves responses by retrieving relevant information first.'),

-- 28 ── NEW ───────────────────────────────────────────────────
('general', 'embedding', 'Embedding',
 'An embedding is a numerical representation of content that helps AI compare meaning and similarity.',
 'Search and Knowledge', 'beginner', true,
 'An embedding is a numerical representation of content that helps AI compare meaning and similarity.',
 'It converts text or other data into numbers so systems can search and group information by meaning.',
 'A system uses embeddings to find documents similar to a user''s question, even if the exact wording is different.',
 'Embeddings are a key concept behind semantic search and many RAG systems.',
 'Thinking embeddings are something users will see directly. They are usually part of the backend logic.',
 ARRAY['Vector Database','Semantic Search','RAG'],
 'What do embeddings help AI systems do?', 'multiple_choice',
 'Compare meaning and similarity',
 'Paint walls',
 'Increase speaker volume',
 'Format paper documents',
 'A',
 'Embeddings help systems compare content by meaning rather than exact wording.'),

-- 29 ─────────────────────────────────────────────────────────
('general', 'vector-database', 'Vector Database',
 'A vector database stores embeddings so AI systems can search for similar content efficiently.',
 'Search and Knowledge', 'intermediate', true,
 'A vector database stores embeddings so AI systems can search for similar content efficiently.',
 'It is a special kind of database designed for similarity search instead of only exact keyword matching.',
 'A support chatbot searches a vector database to find the most relevant help articles for a question.',
 'This is an important backend concept in many modern AI applications.',
 'Assuming a vector database replaces every other database. It usually complements traditional data storage.',
 ARRAY['Embedding','Semantic Search','RAG'],
 'Why would an AI app use a vector database?', 'multiple_choice',
 'To find content based on similarity',
 'To replace electricity',
 'To hide the login page',
 'To print receipts only',
 'A',
 'Vector databases are designed for similarity search using embeddings.'),

-- 30 ── NEW ───────────────────────────────────────────────────
('general', 'semantic-search', 'Semantic Search',
 'Semantic search looks for results based on meaning, not just exact words.',
 'Search and Knowledge', 'beginner', true,
 'Semantic search looks for results based on meaning, not just exact words.',
 'It tries to understand what the user is asking so it can find related content even if the wording is different.',
 'A user searches how to avoid made-up AI answers and finds content about hallucinations.',
 'This helps explain why modern AI search feels smarter than traditional keyword-only search.',
 'Thinking semantic search always understands perfectly. It still depends on good data and system design.',
 ARRAY['Embedding','Vector Database','RAG'],
 'What makes semantic search different?', 'multiple_choice',
 'It focuses on meaning, not only exact keywords',
 'It only works with photos',
 'It ignores user questions',
 'It turns off the internet',
 'A',
 'Semantic search tries to match intent and meaning, not just exact text.'),

-- 31 ── NEW ───────────────────────────────────────────────────
('general', 'human-oversight', 'Human Oversight',
 'Human oversight means people remain responsible for reviewing, guiding, or approving AI-supported work.',
 'Risk and Ethics', 'beginner', true,
 'Human oversight means people remain responsible for reviewing, guiding, or approving AI-supported work.',
 'AI can assist, but people still need to check important outputs, decisions, and risks.',
 'A manager reviews an AI-generated report before it is sent to a client.',
 'This is one of the most practical controls for reducing harm from errors, bias, and hallucinations.',
 'Assuming that because AI is fast, it should be trusted without review.',
 ARRAY['Hallucination','Governance','Explainability'],
 'What is the purpose of human oversight in AI use?', 'multiple_choice',
 'To review and remain accountable for important AI-supported work',
 'To make AI disappear',
 'To slow all software permanently',
 'To block all learning',
 'A',
 'Human oversight keeps people accountable and helps catch errors or risks.'),

-- 32 ── NEW ───────────────────────────────────────────────────
('general', 'guardrail', 'Guardrail',
 'A guardrail is a rule, limit, or control used to guide AI behavior and reduce risky outputs.',
 'Prompting', 'beginner', true,
 'A guardrail is a rule, limit, or control used to guide AI behavior and reduce risky outputs.',
 'It helps keep the system within safe or useful boundaries.',
 'A company configures an internal AI tool not to answer questions outside approved policy documents.',
 'Guardrails are part of building safer and more reliable AI systems.',
 'Thinking one guardrail solves every issue. Usually several controls work together.',
 ARRAY['Governance','Constraint','Human Oversight'],
 'What does a guardrail do in AI?', 'multiple_choice',
 'Sets boundaries or controls on system behavior',
 'Repairs roads',
 'Stores only video files',
 'Changes Wi-Fi settings',
 'A',
 'A guardrail helps keep the AI within intended limits.')

ON CONFLICT (slug, vertical_id) DO UPDATE SET
  -- Enrich new columns for ALL terms (existing + new)
  short_definition  = EXCLUDED.short_definition,
  plain_explanation = EXCLUDED.plain_explanation,
  use_case          = EXCLUDED.use_case,
  why_it_matters    = EXCLUDED.why_it_matters,
  common_mistake    = EXCLUDED.common_mistake,
  related_terms     = EXCLUDED.related_terms,
  quiz_question     = EXCLUDED.quiz_question,
  quiz_type         = EXCLUDED.quiz_type,
  option_a          = EXCLUDED.option_a,
  option_b          = EXCLUDED.option_b,
  option_c          = EXCLUDED.option_c,
  option_d          = EXCLUDED.option_d,
  correct_answer    = EXCLUDED.correct_answer,
  quiz_explanation  = EXCLUDED.quiz_explanation,
  -- Ensure all 32 are published and in general vertical
  published         = true,
  vertical_id       = 'general';
  -- NOTE: definition, term, category, difficulty NOT overwritten for existing rows
